/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as InfloatApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const WebsiteIngestionRequest: core.serialization.Schema<
    serializers.WebsiteIngestionRequest.Raw,
    InfloatApi.WebsiteIngestionRequest
> = core.serialization.object({
    url: core.serialization.string(),
    chatbotId: core.serialization.property("chatbot_id", core.serialization.string()),
    maxDepth: core.serialization.property("max_depth", core.serialization.number().optional()),
});

export declare namespace WebsiteIngestionRequest {
    interface Raw {
        url: string;
        chatbot_id: string;
        max_depth?: number | null;
    }
}
