/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as InfloatApi from "../../api/index";
import * as core from "../../core";
import { ClientResponse } from "../types/ClientResponse";

export const Response: core.serialization.Schema<
    serializers.getClientsProjectsProjectIdClientsGet.Response.Raw,
    InfloatApi.ClientResponse[]
> = core.serialization.list(ClientResponse);

export declare namespace Response {
    type Raw = ClientResponse.Raw[];
}
