/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as InfloatApi from "../../api/index";
import * as core from "../../core";
import { ModelResponse } from "../types/ModelResponse";

export const Response: core.serialization.Schema<
    serializers.getModelsProjectsProjectIdModelsGet.Response.Raw,
    InfloatApi.ModelResponse[]
> = core.serialization.list(ModelResponse);

export declare namespace Response {
    type Raw = ModelResponse.Raw[];
}
