/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as InfloatApi from "../../api/index";
import * as core from "../../core";
import { TrainingStatus } from "../types/TrainingStatus";

export const Response: core.serialization.Schema<
    serializers.getTrainingsProjectsProjectIdTrainingsGet.Response.Raw,
    InfloatApi.TrainingStatus[]
> = core.serialization.list(TrainingStatus);

export declare namespace Response {
    type Raw = TrainingStatus.Raw[];
}
