/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as InfloatApi from "../../api/index";
import * as core from "../../core";
import { TrainingResultResponse } from "../types/TrainingResultResponse";

export const Response: core.serialization.Schema<
    serializers.getTrainingResultsTrainingsTrainingIdResultsGet.Response.Raw,
    InfloatApi.TrainingResultResponse[]
> = core.serialization.list(TrainingResultResponse);

export declare namespace Response {
    type Raw = TrainingResultResponse.Raw[];
}
