/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         uniqueCode: "unique_code",
 *         query: "query"
 *     }
 */
export interface ChatbotApiV1ChatbotChatCompletionsGetRequest {
    uniqueCode: string;
    query: string;
}
