/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class InfloatApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, InfloatApiTimeoutError.prototype);
    }
}
