/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../index";
import * as InfloatApi from "../../../api/index";
import * as core from "../../../core";

export const ProjectCreate: core.serialization.Schema<
    serializers.ProjectCreate.Raw,
    Omit<InfloatApi.ProjectCreate, "authorization">
> = core.serialization.object({
    name: core.serialization.string(),
    description: core.serialization.string().optional(),
    isPublic: core.serialization.property("is_public", core.serialization.boolean().optional()),
});

export declare namespace ProjectCreate {
    interface Raw {
        name: string;
        description?: string | null;
        is_public?: boolean | null;
    }
}
