/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../index";
import * as InfloatApi from "../../../api/index";
import * as core from "../../../core";

export const UserAuth: core.serialization.Schema<serializers.UserAuth.Raw, InfloatApi.UserAuth> =
    core.serialization.object({
        email: core.serialization.string(),
        password: core.serialization.string(),
    });

export declare namespace UserAuth {
    interface Raw {
        email: string;
        password: string;
    }
}
