/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../index";
import * as InfloatApi from "../../../api/index";
import * as core from "../../../core";

export const UserCreate: core.serialization.Schema<serializers.UserCreate.Raw, InfloatApi.UserCreate> =
    core.serialization.object({
        name: core.serialization.string(),
        email: core.serialization.string(),
        password: core.serialization.string(),
    });

export declare namespace UserCreate {
    interface Raw {
        name: string;
        email: string;
        password: string;
    }
}
