/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as InfloatApi from "../index";

export interface ChatbotResponse {
    id: string;
    name: string;
    userId: string;
    documents?: InfloatApi.DocumentResponse[];
}
