/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ClientConfig {
    modelUrl: string;
    trainingRounds?: number;
    batchSize?: number;
    learningRate?: number;
    optimizer?: string;
    additionalConfig?: Record<string, unknown>;
}
