/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface DocumentResponse {
    id: string;
    chatbotId: string;
    url?: string;
    filePath: string;
    fileType: string;
    uploadedAt?: Date;
}
