/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ModelResponse {
    id: string;
    filename: string;
    url?: string;
    modelType?: string;
    version?: string;
    createdAt: Date;
}
