/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ProjectResponse {
    id: string;
    name: string;
    description?: string;
    createdAt: Date;
    updatedAt: Date;
    isPublic: boolean;
    ownerId: string;
}
