/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TrainingStatus {
    id: string;
    status: string;
    currentRound: number;
    targetRounds: number;
    startTime?: Date;
    endTime?: Date;
    aggregatedMetrics?: Record<string, unknown>;
}
