/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TrainingResultResponse {
    clientId: string;
    round: number;
    loss: number;
    accuracy: number;
    metrics?: Record<string, unknown>;
    timestamp: Date;
}
