/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as InfloatApi from "../index";

export interface ValidationError {
    loc: InfloatApi.ValidationErrorLocItem[];
    msg: string;
    type: string;
}
