/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         clientId: "client_id",
 *         round: 1,
 *         loss: 1.1,
 *         accuracy: 1.1,
 *         trainingSamples: 1,
 *         trainingTime: 1.1
 *     }
 */
export interface ClientMetrics {
    apiKey?: string;
    clientId: string;
    round: number;
    loss: number;
    accuracy: number;
    trainingSamples: number;
    trainingTime: number;
    additionalMetrics?: Record<string, unknown>;
}
