/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface GetTrainingResultsTrainingsTrainingIdResultsGetRequest {
    roundNum?: number;
    authorization?: string;
}
