/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface GetTrainingsProjectsProjectIdTrainingsGetRequest {
    skip?: number;
    limit?: number;
    authorization?: string;
}
