/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         name: "name"
 *     }
 */
export interface ProjectCreate {
    authorization?: string;
    name: string;
    description?: string;
    isPublic?: boolean;
}
