/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         modelId: "model_id"
 *     }
 */
export interface TrainingCreate {
    authorization?: string;
    modelId: string;
    targetRounds?: number;
    minClients?: number;
    maxClients?: number;
    aggregationStrategy?: string;
    config?: Record<string, unknown>;
}
