/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         name: "name",
 *         email: "email",
 *         password: "password"
 *     }
 */
export interface UserCreate {
    name: string;
    email: string;
    password: string;
}
