/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as InfloatApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const LoginSchema: core.serialization.Schema<
    serializers.LoginSchema.Raw,
    Omit<InfloatApi.LoginSchema, "provider">
> = core.serialization.object({
    email: core.serialization.string(),
    password: core.serialization.string(),
});

export declare namespace LoginSchema {
    export interface Raw {
        email: string;
        password: string;
    }
}
