/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as InfloatApi from "../../api/index";
import * as core from "../../core";

export const BodyCreateChatbotApiV1ChatbotPost: core.serialization.ObjectSchema<
    serializers.BodyCreateChatbotApiV1ChatbotPost.Raw,
    InfloatApi.BodyCreateChatbotApiV1ChatbotPost
> = core.serialization.object({
    chatbotName: core.serialization.property("chatbot_name", core.serialization.string()),
});

export declare namespace BodyCreateChatbotApiV1ChatbotPost {
    interface Raw {
        chatbot_name: string;
    }
}
