/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as InfloatApi from "../../api/index";
import * as core from "../../core";

export const BodyIngestYoutubeApiV1IngestYoutubePost: core.serialization.ObjectSchema<
    serializers.BodyIngestYoutubeApiV1IngestYoutubePost.Raw,
    InfloatApi.BodyIngestYoutubeApiV1IngestYoutubePost
> = core.serialization.object({
    url: core.serialization.string(),
    chatbotId: core.serialization.property("chatbot_id", core.serialization.string()),
});

export declare namespace BodyIngestYoutubeApiV1IngestYoutubePost {
    export interface Raw {
        url: string;
        chatbot_id: string;
    }
}
