/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as InfloatApi from "../../api/index";
import * as core from "../../core";

export const ClientResponse: core.serialization.ObjectSchema<
    serializers.ClientResponse.Raw,
    InfloatApi.ClientResponse
> = core.serialization.object({
    id: core.serialization.string(),
    name: core.serialization.string().optional(),
    apiKey: core.serialization.property("api_key", core.serialization.string()),
    createdAt: core.serialization.property("created_at", core.serialization.date()),
});

export declare namespace ClientResponse {
    interface Raw {
        id: string;
        name?: string | null;
        api_key: string;
        created_at: string;
    }
}
