/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as InfloatApi from "../../api/index";
import * as core from "../../core";

export const DocumentResponse: core.serialization.ObjectSchema<
    serializers.DocumentResponse.Raw,
    InfloatApi.DocumentResponse
> = core.serialization.object({
    id: core.serialization.string(),
    chatbotId: core.serialization.property("chatbot_id", core.serialization.string()),
    url: core.serialization.string().optional(),
    filePath: core.serialization.property("file_path", core.serialization.string()),
    fileType: core.serialization.property("file_type", core.serialization.string()),
    uploadedAt: core.serialization.property("uploaded_at", core.serialization.date().optional()),
});

export declare namespace DocumentResponse {
    interface Raw {
        id: string;
        chatbot_id: string;
        url?: string | null;
        file_path: string;
        file_type: string;
        uploaded_at?: string | null;
    }
}
