/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as InfloatApi from "../../api/index";
import * as core from "../../core";

export const ModelResponse: core.serialization.ObjectSchema<serializers.ModelResponse.Raw, InfloatApi.ModelResponse> =
    core.serialization.object({
        id: core.serialization.string(),
        filename: core.serialization.string(),
        url: core.serialization.string().optional(),
        modelType: core.serialization.property("model_type", core.serialization.string().optional()),
        version: core.serialization.string().optional(),
        createdAt: core.serialization.property("created_at", core.serialization.date()),
    });

export declare namespace ModelResponse {
    interface Raw {
        id: string;
        filename: string;
        url?: string | null;
        model_type?: string | null;
        version?: string | null;
        created_at: string;
    }
}
