/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as InfloatApi from "../../api/index";
import * as core from "../../core";

export const Token: core.serialization.ObjectSchema<serializers.Token.Raw, InfloatApi.Token> =
    core.serialization.object({
        accessToken: core.serialization.property("access_token", core.serialization.string()),
        tokenType: core.serialization.property("token_type", core.serialization.string()),
    });

export declare namespace Token {
    interface Raw {
        access_token: string;
        token_type: string;
    }
}
