/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as InfloatApi from "../../api/index";
import * as core from "../../core";

export const TrainingResultResponse: core.serialization.ObjectSchema<
    serializers.TrainingResultResponse.Raw,
    InfloatApi.TrainingResultResponse
> = core.serialization.object({
    clientId: core.serialization.property("client_id", core.serialization.string()),
    round: core.serialization.number(),
    loss: core.serialization.number(),
    accuracy: core.serialization.number(),
    metrics: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    timestamp: core.serialization.date(),
});

export declare namespace TrainingResultResponse {
    interface Raw {
        client_id: string;
        round: number;
        loss: number;
        accuracy: number;
        metrics?: Record<string, unknown> | null;
        timestamp: string;
    }
}
