/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as InfloatApi from "../../api/index";
import * as core from "../../core";

export const YoutubeTranscript: core.serialization.ObjectSchema<
    serializers.YoutubeTranscript.Raw,
    InfloatApi.YoutubeTranscript
> = core.serialization.object({
    transcript: core.serialization.string(),
    videoId: core.serialization.property("video_id", core.serialization.string()),
});

export declare namespace YoutubeTranscript {
    interface Raw {
        transcript: string;
        video_id: string;
    }
}
