/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         chatbotId: "chatbot_id"
 *     }
 */
export interface BodyUploadDocumentApiV1IngestDocumentPost {
    chatbotId: string;
}
