/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const InfloatApiEnvironment = {
    Default: "http://localhost:8000",
} as const;

export type InfloatApiEnvironment = typeof InfloatApiEnvironment.Default;
